spring:
  config:
    import:
      - optional:configserver:http://ms-configserver:8888
  application:
    name: payment-service
  data:
    mongodb:
      database: db_payment
      host: localhost
      port: 27022
server:
  port: 8085
management:
  endpoint:
    web:
      exposure:
        include: "*"
message:
  path-payment: /api/v1/payments