server:
  port: 8085
spring:
  application:
    name: payment-service
  config:
    import:
      - optional:configserver:https://ms-config.azurewebsites.net
  data:
    mongodb:
      uri: mongodb+srv://admin:5K8yj70q4RpuiBSE@bootcamp37.anglhbu.mongodb.net/db_payment
eureka:
  client:
    service-url:
      defaultZone: https://ms-discovery.azurewebsites.net/eureka/
management:
  endpoint:
    web:
      exposure:
        include: "*"
message:
  path-payment: /api/v1/payments
  path-customerProductDomain: https://ms-customerproduct.azurewebsites.net
  path-get: /api/v1/customerActivesProducts/
  path-update: /api/v1/customerActivesProducts/update/
resilience4j:
  circuitbreaker:
    instances:
      ms-customerProduct:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimumNumberOfCalls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        waitDurationInOpenState: 2s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED